Django/Django/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('taf.urls')),
    
]

Django/Django/myproject/taf/urls.py
from django.urls import path
from . import views
from .views import create_task, delete_task, edit_task



urlpatterns =[
    path('', views.main, name='main'),
    path('task_list/', views.task_list, name="task_list"),
    path('task_list/details/<int:id>', views.details, name='details'),
    path('signup_page/', views.signup_page, name='signup_page'),
    path('logout_page/', views.logout_page, name='logout_page'),
    path('create_task/', create_task, name="create_task"),
    path('delete_task/<int:pk>', delete_task, name='delete_task'),
    path('edit_task/<int:pk>', edit_task, name='edit_task'),
    
]

Django/Django/myproject/taf/models.py
from django.db import models
from django.contrib.auth.models import User
import pycountry

# Create your models here.
"""
class Users(models.Model):
    name = models.CharField(max_length=64, default=False)
    surname = models.CharField(max_length=64, default=False)
    username = models.CharField(max_length=64, default=False)
    COUNTRY_CHOICES = [(country.alpha_2, country.name) for country in pycountry.countries]
    country = models.CharField(choices=COUNTRY_CHOICES, max_length=3, null=False, help_text="Please select an area code")
    city = models.CharField(max_length=64, default=False)
    created_time = models.DateTimeField(auto_now_add=True)
"""
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    title =models.CharField(max_length =200)
    description = models.TextField(max_length=1000)
    STATUS_CHOICES = [('scheduled','Scheduled'),('completed','Completed'),('cancelled','Cancelled')]
    status = models.CharField(choices=STATUS_CHOICES, default='scheduled', max_length=15)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    created_on = models.DateField(auto_now_add =True)


    def __str__(self):
        return f'{self.title}'
    
    def snippet(self):
        return self.description[:50] +'...'
    


Django/Django/myproject/taf/forms.py
from django import forms
from .models import User, Task
import pycountry
from django.contrib.auth import password_validation



class UserCreationForm(forms.ModelForm):
    COUNTRY_CHOICES = [(country.alpha_2, country.name) for country in pycountry.countries]
    country = forms.ChoiceField(choices=COUNTRY_CHOICES, required=False, help_text="Please select an area code")
    city = forms.CharField(max_length=64)
    #created_time = forms.DateTimeField(auto_now_add=True)
    name = forms.CharField(max_length=64)
    surname = forms.CharField(max_length=64)
    username = forms.CharField(max_length=64)

    class Meta:
        model = User
        fields = ['name', 'surname', 'username', 'country', 'city']


    def clean_password2(self):
        password2 = super().clean_password2()
        username = self.cleaned_data.get('username')
  
        if username and password2 and password2 in username:
           raise forms.ValidationError(
                                self.error_messages['password_similar_username'],
                                code='password_similar_username',
                                )
  
           password_validation.validate_password(password2, self.instance)
  
        return password2



class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description', 'status', 'start_time', 'end_time']

Django/Django/myproject/taf/views.py
from django.shortcuts import render, redirect, get_object_or_404, redirect
from django.http import HttpResponse
from django.template import loader
from . models import Task
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.views.generic.edit import CreateView, DeleteView
from django.urls import reverse_lazy
from .forms import TaskForm
# Create your views here.



def task_list(request):
    tasks =Task.objects.all().values()
    template =loader.get_template('taf/task_list.html')
    context ={
        'tasks':tasks
    }
    return render(request, 'taf/task_list.html', context)



def details(request, id):
    task = Task.objects.get(id=id)
    template = loader.get_template('taf/details.html')
    context = {
        'task': task,
    }
    return HttpResponse(template.render(context, request))


@csrf_exempt
def signup_page(request):
    template = loader.get_template('taf/signup_page.html')
    if request.method =='POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # Log the user in if needed
            return redirect('task_list')  # Assuming 'task_list' is a valid URL name
    else:
        form = UserCreationForm()
    context ={
        'form': form
    }
    return HttpResponse(template.render(context, request))



def logout_page(request):
    logout(request)
    template = loader.get_template('taf/signup_page.html')
    return HttpResponse(template.render())

"""
def create_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('task_list')
    else:
        form = TaskForm()
    template = loader.get_template('taf/create_task.html')
    context = {
        'form': form
    }
    return render(request, 'taf/create_task.html', context)
"""
def create_task(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            # Associate the current user with the task
            task = form.save(commit=False)
            task.user = request.user  # Assign the current user
            task.save()
            return redirect('task_list')
    else:
        form = TaskForm()
    context = {
        'form': form
    }
    return render(request, 'taf/create_task.html', context)


def edit_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return redirect('task_list')
    else:
        form = TaskForm(instance=task)
    template = loader.get_template('taf/edit_task.html')
    context = {
        'form': form
    }
    return render(request, 'taf/edit_task.html', context)

def delete_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    if request.method == 'POST':
        task.delete()
        return redirect('task_list')
    template = loader.get_template('taf/task_confirm_delete.html')
    context = {
        'task': task
    }
    return HttpResponse(template.render(context, request))

def main(request):
    task_id = request.GET.get('id')
    if task_id is not None:
        try:
            task = Task.objects.get(id=task_id)
        except Task.DoesNotExist:
            task = None
    else:
        task = None

    context = {
        'task': task,
    }
    return render(request, 'taf/main.html', context)

Django/Django/myproject/taf/templates/taf/create_task.html
<h1>Create your task here</h1>

<form method="post" action="{% url 'create_task' %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="id_title">Title:</label>
        <input type="text" id="id_title" name="title" class="form-control" value="{{ form.title.value }}" required>
    </div>
    <div class="form-group">
        <label for="id_description">Description:</label>
        <textarea id="id_description" name="description" class="form-control" required>{{ form.description.value }}</textarea>
    </div>
    <div class="form-group">
        <label for="id_status">Status:</label>
        <select id="id_status" name="status" class="form-control" required>
            {% for value, label in form.fields.status.choices %}
                <option value="{{ value }}" {% if form.status.value == value %} selected {% endif %}>{{ label }}</option>
            {% endfor %}
        </select>
    </div>
    <div class="form-group">
        <label for="id_start_time">Start Time:</label>
        <input type="datetime-local" id="id_start_time" name="start_time" class="form-control" value="{{ form.start_time.value|date:'Y-m-d\TH:i' }}" required>
    </div>
    <div class="form-group">
        <label for="id_end_time">End Time:</label>
        <input type="datetime-local" id="id_end_time" name="end_time" class="form-control" value="{{ form.end_time.value|date:'Y-m-d\TH:i' }}" required>
    </div>
    <input type="submit" value="Submit">
</form>


Django/Django/myproject/taf/templates/taf/details.html
{% extends "taf/general.html"%}

{% block title %}
    <h1>{{ task.title }}</h1>
{%endblock%} 

{%block content %}
    <p>Description: {{ task.description }}</p>
    <p>completed: {{ task.completed }}</p>
    <p>Created on: {{ task.created_on }}</p>
    
    
    <p>Back to <a href="{% url 'task_list' %}">Your tasks</a></p>

{%endblock%}

Django/Django/myproject/taf/templates/taf/edit_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Task</title>
</head>
<body>
    <h1>Edit Task</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Task</button>
    </form>
</body>
</html>

Django/Django/myproject/taf/templates/taf/general.html
<!DOCTYPE html>
<html>
<head>
  <title>{% block title %}{% endblock %}</title>
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>
<body>






{% block content %}
{% endblock %}

</body>
</html>  

Django/Django/myproject/taf/templates/taf/main.html
{% block title %}
{% endblock %}

{% block content %}
<div class="container">
  <h1>Welcome to our Task Management App</h1>

  <h3>My Tasks</h3>
  
  <p>Please <a href="{% url 'signup_page' %}" class="signup_page">signup</a> to manage your tasks.</p>
</div>

<style>
  body {
    font-family: 'Arial', sans-serif;
    background: linear-gradient(to bottom right, #3498db, #2c3e50);
    margin: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    min-height: 100vh; /* Ensure full-height view */
    color: #fff;
  }

  .container {
    max-width: 600px;
    padding: 40px;
    background: rgba(255, 255, 255, 0.9);
    border-radius: 15px;
    box-shadow: 0 5px 15px rgba(0, 0, 0, 0.3);
    text-align: center;
  }

  h1, h3 {
    color: #333;
  }

 p {
    color:black;
    
 }
 a {
  text-decoration: none; 
  color: #3498db; 
}
 

  
</style>

{% endblock %}
    
  
    
  
    

Django/Django/myproject/taf/templates/taf/signup_page.html
<!DOCTYPE html>
<html>
<head>
  <title>Sign Up</title>
</head>
<body>

   <h2>Testing my sign up page</h2>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="card">
                <div class="card-body">
                    <h1 class="h3 mb-3 fw-normal">Please sign up</h1>
                    <form class="site-form" action="{% url 'task_list' %}" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="username" class="form-label">Username:</label>
                            <input type="text" id="username" name="username" class="form-control" required>
                        </div>
                        <div class="mb-3">
                            <label for="name" class="form-label">Name:</label>
                            <input type="text" id="name" name="name" class="form-control" required>
                        </div>
                        <div class="mb-3">
                            <label for="surname" class="form-label">Surname:</label>
                            <input type="text" id="surname" name="surname" class="form-control" required>
                        </div>
                        <div class="mb-3">
                            <label for="country" class="form-label">Country:</label>
                            <input type="text" id="country" name="country" class="form-control" required>
                        </div>
                        <div class="mb-3">
                            <label for="city" class="form-label">City:</label>
                            <input type="text" id="city" name="city" class="form-control" required>
                        </div>
                        <div class="mb-3">
                            <label for="password1" class="form-label">Password:</label>
                            <input type="password" id="password1" name="password1" class="form-control" required>
                        </div>
                        <div class="mb-3">
                            <label for="password2" class="form-label">Confirm Password:</label>
                            <input type="password" id="password2" name="password2" class="form-control" required>
                        </div>
                        <input type="submit" value="Signup" class="btn btn-primary">
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

</body>
</html>

Django/Django/myproject/taf/templates/taf/task_confirm_delete.html
<p><a href="{% url 'task_list' %}">Go back</a></p>

<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete this task? "{{tk}}"</p>
    <input type="submit" value="Delete"/>
</form>

Django/Django/myproject/taf/templates/taf/task_list.html
{% extends "taf/general.html" %}

{% block title %}
  Task management app - List of all your tasks
{% endblock %}

{% block content %}
  <div class="container">
    <h1>Task List</h1>

    <p><a href="{% url 'task_list' %}">Task List</a></p>

    <div class="task-list">
      <h2>Your Tasks</h2>
      <ul>
        {% for t in tasks %}
          <li>
            <div class="task-info">
              <a href="details/{{ t.id }}">{{ t.title }}</a>
              <span class="created-on">{{ t.created_on }}</span>
            </div>
            <div class="actions">
              <a href="{% url 'delete_task' pk=t.id %}" class="delete-link">Delete</a>
              <a href="{% url 'edit_task' pk=t.id %}" class="delete-link">Edit</a>
            </div>
          </li>
        {% endfor %}
      </ul>
    </div>

    <div class="actions">
      <a href="{% url 'create_task' %}" class="add-task-link">Add Task</a>
      <a href="{% url 'signup_page' %}" class="sign-up-link">Log Out</a>
    </div>
  </div>

  <style>
    body {
      font-family: 'Arial', sans-serif;
      background-color: #f4f4f4;
    }

    .container {
      max-inline-size: 800px;
      margin: 0 auto;
      padding: 20px;
      background-color: #fff;
      border-radius: 5px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
    }

    h1, h2 {
      color: #333;
    }
    a {
      text-decoration: none; 
       
    }

    .task-list {
      margin-block-start: 20px;
    }

    ul {
      list-style-type: none;
      padding: 0;
    }

    li {
      background-color: #f9f9f9;
      margin-block-end: 10px;
      padding: 10px;
      border-radius: 5px;
      display: flex;
      justify-content: space-between;
    }

    .task-info {
      flex-grow: 1;
    }

    .created-on {
      font-size: 12px;
      color: #888;
    }

    .actions {
      text-align: end;
    }

    .delete-link {
      color: #e74c3c;
      text-decoration: none;
      margin-inline-start: 10px;
    }

    .add-task-link, .sign-up-link, .logout-link {
      display: inline-block;
      margin-block-start: 20px;
      padding: 10px;
      color: #fff;
      text-decoration: none;
      background-color: #3498db;
      border-radius: 5px;
      transition: background-color 0.3s;
    }

    .add-task-link:hover, .sign-up-link:hover, .logout-link:hover {
      background-color: #2980b9;
    }
  </style>
{% endblock %}